# Generated by Django 2.2.4 on 2019-12-13 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default=None)),
                ('floor', models.IntegerField(blank=True, default=None, null=True)),
                ('building', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='places_app.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default=None)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='places_app.Room')),
            ],
        ),
    ]
